#STAGE 1
FROM node:18-slim as builder
WORKDIR /app
COPY package.json ./
COPY package-lock.json ./
COPY . .
RUN npm cache clean --force
RUN npm install
RUN npm run build

#STAGE 2
FROM nginx
WORKDIR /app
COPY --from=builder /app/nginx/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/dist /usr/share/nginx/html
