# Stage 1: Build the application
FROM node:20.16-alpine3.19 AS build

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json (if available)
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Build the application
RUN npm run build

# Stage 2: Serve the application
FROM node:20.16-alpine3.19 AS production

# Install serve globally
RUN npm install -g serve

# Set the working directory
WORKDIR /app

# Copy the build artifacts from the build stage
COPY --from=build /app/dist ./dist

# Expose the port Vite will run on
EXPOSE 3000

# Command to serve the built application
CMD ["serve", "-s", "dist"]
