services: 
  online_shop: # Service name 
    image: varundev121/online-shop # Docker image 
    container_name: online_shop # Custom container name 
    ports: # Map host:container port
      - "3000:5173" 
    restart: always # AutoRestart policy
