# Base image
FROM node:20.16-alpine3.19 

# Working directory
WORKDIR /app

# Copy package.json and package-lock.json (if available)
COPY package*.json .

RUN npm install

# Install dependencies, including dev dependencies to ensure Vite is installed
RUN npm i -g serve
# Copy the rest of the application code
COPY . .

RUN npm run build

# Expose the port Vite will run on
EXPOSE 3000

# Command to run the development server
CMD [ "serve", "-s", "dist" ]
