# Stage 1
FROM node:18-alpine AS builder
WORKDIR /app
COPY package.json ./
COPY package-lock.json ./
# Inside package.json file we have lib details so we will install only for required dependencies for make docker image light.
RUN npm install --only=dependencies 
# copy rest of the code 
COPY . .

# Stage 2
FROM node:18-alpine
WORKDIR /app
COPY --from=builder /app /app
RUN npm run build
EXPOSE 3000
CMD [ "npm","run","dev" ]